### ISSUE TITLE
Consider alternative for chest labeling.

### ISSUE THREAD

**Issue by NickGrease** [henne90gen/ChestCounter#10]
I'm not sure if forge has the ability to add buttons to the top of inventory screens, if it does, consider using a button in place of the text box that opens a gui to add a label.  Your current implementation covers buttons that are usually at the top for different inventory sorting mods.

**Comment by henne90gen** [comment]
I'll see what I can do.
Maybe just changing the position of the text field would be sufficient.
I could move it above the name of the container.

**Comment by NickGrease** [comment]
For reference - my inventory screen. Notice the buttons at the top. Some mods have 2-4 buttons there. Whatever you can do would be appreciated.

![2020-06-08_18 11 32](https://user-images.githubusercontent.com/854582/84085661-17febf80-a9b4-11ea-9a72-eb6c732df774.png)

**Comment by henne90gen** [comment]
I moved the text field above the inventory screen.
This way it will not collide with any buttons.
Version 2.0.0-69 should contain the changes.
PS: PureBDCraft is my favorite texture pack as well :D
