### ISSUE TITLE
Shortcut to hide search not working.

### ISSUE THREAD

**Issue by NickGrease** [henne90gen/ChestCounter#13]
2.0.69
May be related to #12 but the shortcut to hide inventory search/listing is not working. The shortcut to turn of/off the mod works fine. 

A Suggestion - when the user uses a shortcut print out a message to chat - eg. "ChestCounter Enabled/Disabled", "ChestCounter results hidden/visible "

**Comment by henne90gen** [comment]
This should be fixed now.
Could you try version 2.0.75?

**Comment by NickGrease** [comment]
Works like a charm. Thanks again for this mod, glad I found it!

**Comment by henne90gen** [comment]
Awesome! I'm glad it works and I'm glad you like the mod.
