### ISSUE TITLE
Naming of barrels and single chests is broken

### ISSUE THREAD

**Issue by roninvanderwerke** [henne90gen/ChestCounter#3]
When placing a barrel it gets the name of the last chest you opened. And when placing chest with shift so they're separated doesn't s make them separate in the mod, so it sees them as a double chest.

- [x] placed barrel gets the name of the last opened chest
- [ ] shift-placing single chests are detected as double chests

**Comment by henne90gen** [comment]
Thanks for reporting those problems.
I'll have to see when I get around to fixing them.

**Comment by henne90gen** [comment]
@roninvanderwerke, I've fixed the issues you reported.
Check out the newest version on curseforge, to get the update.
