### ISSUE TITLE
Can't Create New World on 1.12.2

### ISSUE THREAD

**Issue by KenyMylankca** [henne90gen/ChestCounter#5]

**Comment by KenyMylankca** [comment]
[crash-2020-04-11_12.34.57-client.txt](https://github.com/henne90gen/ChestCounter/files/4464355/crash-2020-04-11_12.34.57-client.txt)

**Comment by henne90gen** [comment]
I'm sorry, but I can't support older versions of Minecraft.

**Comment by KenyMylankca** [comment]
older? lol. 1.12 isn't old. but looks like youre an amateur modder. good luck.

**Comment by henne90gen** [comment]
I just don't have the time to maintain this mod for more than one version of Minecraft.
If you have some spare time, you are more than welcome to submit a pull request to fix the issue.
