### ISSUE TITLE
Add ability to turn off chest list/contents display (in inventory)

### ISSUE THREAD

**Issue by NickGrease** [henne90gen/ChestCounter#8]
JEI has the ability to hide its GUI (Ctrl+o) - As long as this mods uses the same area, then it **must** have the ability to turn off the GUI like JEI does. If I have to choose between this mod and JEI, the winner is obvious.

**Comment by henne90gen** [comment]
That's a good idea.
What shortcut would you recommend?
I don't use many mods, so I don't really know which shortcut would collide the least with other mods.
Maybe something like ctrl+s (s for search) or ctrl+c (c for chestcounter)?

**Comment by henne90gen** [comment]
You can already turn off the mod completely by setting `enabled` to false in the config section of `chestcount.json`.
I know this is not the same as a dedicated shortcut, but could be a temporary solution until I implement the shortcut.

**Comment by NickGrease** [comment]
I'm not sure (again) what forge capabilities exist, but if your shortcut is automatically added to minecrafts key config area, then it doesn't much matter what you set the default to. As it stands, with even just a few (larger) mods, most A-Z keys are already used, and I mostly use punctuation keys for turning things on and off when available.

**Comment by henne90gen** [comment]
I added the ability to turn off the mod completely by pressing ctrl+c.
The search results can be hidden by pressing ctrl+s.
There is still one more issue with this #12
