### ISSUE TITLE
Config file not in config folder

### ISSUE THREAD

**Issue by NickGrease** [henne90gen/ChestCounter#9]
Currently the config file is in the root minecraft folder (.minecraft) The Read Me suggests its in the config folder. Also the leftside/rightside configuration option doesn't seem to be present (2.0.62)

**Comment by henne90gen** [comment]
I'll take a look and eliminate any inconsistencies between documentation and actual behavior.

**Comment by henne90gen** [comment]
The instructions in the README had confusing wording.
The code also wasn't making sure that the config section would always be there with all the available values.
I fixed both of those issues and the changes should be available with the next release.
